<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\Noticia;

class NoticiaTableSeeder extends Seeder
{
    /**
     * Crear los seeds de la base de datos para
     * el primer admin y usuario.
     */
    public function run()
    {
        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();

        $noticia = new Noticia;
        $noticia->titulo = 'Lorem ipsum dolor sit amet.';
        $noticia->cuerpo = 'Nullam id nibh nec odio ultricies faucibus eu nec metus. Fusce venenatis consectetur nisi nec volutpat. Sed sit amet enim sit amet odio eleifend tincidunt. Donec consectetur, risus et molestie commodo, enim urna rhoncus erat, consectetur pharetra leo dui quis ex. Duis dictum leo eget turpis mollis mattis. Nullam viverra neque justo, sodales suscipit metus tincidunt et. Proin ac pretium metus. Nunc ac sapien interdum, commodo neque ac, mollis arcu. Duis congue efficitur laoreet. Nulla facilisi. Morbi facilisis maximus metus in bibendum. Sed sed nunc feugiat risus imperdiet blandit. Donec sit amet enim a nisl maximus consectetur non et metus. Etiam quis cursus diam.

Duis eleifend dui congue mollis mollis. Aliquam euismod finibus enim, vitae dignissim justo. Etiam ut mi nec est cursus facilisis. Pellentesque pellentesque nisi a accumsan eleifend. Suspendisse a elit non enim accumsan auctor in ut nunc. Donec lacinia fringilla mattis. Proin ornare ultrices feugiat. Nam sollicitudin tortor eget quam dignissim, non cursus ipsum cursus. Curabitur luctus iaculis massa, nec scelerisque libero lacinia sit amet. Vivamus eu elit vehicula, congue purus vitae, convallis velit. Maecenas cursus eu velit sed congue. Fusce ultricies malesuada turpis eu egestas.

Vestibulum sed lacus eget ex rutrum fermentum. Nulla et viverra nisi. Aenean tincidunt malesuada dolor, id facilisis enim scelerisque vel. Integer eget urna pretium, fringilla ante ac, posuere justo. Phasellus imperdiet urna id orci blandit, ac volutpat urna sagittis. Donec ut faucibus mi, eget ultrices sapien. Nullam rhoncus eros et purus commodo imperdiet. Ut a nunc quis ante porta elementum ac nec arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a porta nisl. Ut et turpis ultricies, rutrum ligula ac, tempor ipsum. Vivamus convallis, leo et sollicitudin pretium, massa massa pharetra ante, vitae egestas arcu purus eu risus. Integer consectetur lacinia dolor, sit amet accumsan lectus interdum ut. Vivamus non mollis lorem. Integer ac arcu in dui commodo finibus id ac ipsum.

Donec hendrerit ante vel libero accumsan, at bibendum justo placerat. Phasellus commodo ullamcorper convallis. Praesent finibus, tellus nec eleifend auctor, enim neque dapibus ligula, id suscipit erat sem sit amet nunc. Aliquam eu justo turpis. Aenean auctor malesuada sapien vel sagittis. Mauris tempus malesuada aliquam. Cras ut metus viverra, suscipit orci vestibulum, dictum dui. Phasellus et nibh vel magna aliquam egestas. Vestibulum imperdiet, mi sed iaculis interdum, orci dui hendrerit nibh, ac aliquam sapien enim vitae ex. Quisque in est sapien. In vel fermentum arcu.

Donec non elit rutrum, fermentum risus in, dapibus eros. Mauris at ultrices eros, sed porta nisi. In aliquet maximus arcu, id sagittis tellus faucibus sit amet. Donec volutpat euismod libero, nec consequat risus mollis cursus. Pellentesque tempor cursus laoreet. Donec scelerisque auctor dolor, sit amet cursus arcu. In et dui nec dolor dapibus malesuada. Nullam lacinia venenatis aliquet. Aliquam non mattis nibh. Cras quis venenatis arcu. Vivamus at interdum ligula. Sed pretium lectus vel massa semper fringilla. Integer vel lorem augue.';
        $noticia->save();
    }
}
